### ISSUE TITLE
LOC of nlohmann/json

### ISSUE THREAD

**Issue by nlohmann** [iodcpp/metajson#1]
To be fair: nlohmann/json has 14478 LOC, but only 2867 "relevant" (i.e., no whitespace or comments), see https://coveralls.io/builds/11822477.

**Comment by matt-42** [comment]
Indeed, it was not fair for  nlohmann/json. When using sloccount, it is only 5.5x smaller. I do not know the number of relevant lines from coveralls.io for metajson so I cannot make a comparison with this metric, so I just removed this comparison.

**Comment by nlohmann** [comment]
Thanks. Your performance numbers are impressive, and I will definitely have a look at this. (I just didn't want to be "shamed" for having lots of comments ;-))

You still have

> Code size: Up to 8x smaller than nlohmann/json and 2x smaller than rapidjson.

in the README.

**Comment by matt-42** [comment]
Thanks, your feedback is welcome.
The code size comparison was about the size of the compiled binary executable. You'll find the source code of this comparison here (basically just the decoding of one array of float):
https://github.com/iodcpp/metajson/tree/master/benchmarks/decode_float_array_*.cc

Also note that metajson handle a subset of what nlohmann/json can hande : It target cases where the structure of the json body is known at compile time.

**Comment by nlohmann** [comment]
Indeed, you comparing apples with oranges, because nlohmann/json does a lot more than parsing.

**Comment by matt-42** [comment]
This is not a exhaustive benchmark, which is not the goal of this project. I am briefly comparing rapidjson,  nlohmann/json and metajson, three working JSON de/serializers.
We make think of this comparison as unfair because metajson uses a static paradigm (everything is know at compile time), but being fair was not the goal here :
The main contribution of this work is to show that we can generate better code when the structure of the json objects are know at compile time, and propose a framework that implement this idea.
